//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetActivityLog
    {
        public string ActivityDetail { get; set; }
        public string ActivityTime { get; set; }
        public string FullName { get; set; }
    }
}
